#----------------------必须配置--------------------------------------------------------
bot:
  #机器人的qq号
  qq: 2068468537

onebot:
  socket:
    # 机器人实现端的ws地址
    url: ws://localhost:8282
    # 断线重连等待时间（毫秒）
    reconnectTime: 5000

# 数据库配置
mysql:
  address: localhost:3306/bb_bot
  username: root
  password: root

file:
  #文件保存目录
  path: /bot/static/

#----------------------可选配置--------------------------------------------------------
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8199

spring:
  #配置文件
  profiles:
    active: local
  #mysql druid数据源相关配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://${mysql.address}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
      username: ${mysql.username}
      password: ${mysql.password}
      # 初始连接数
      initialSize: 10
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 30
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: false
      statViewServlet:
        enabled: false