#----------------------必须配置--------------------------------------------------------
bot:
  #类型：onebot（oneBot规范机器人），qqnt，qq（QQ官方机器人）
  onebot:
    #自定义机器人名称
    bot1:
      #是否启用
      enable: false
      #机器人的qq号
      qq: 111111111
      #机器人的webSocket配置
      webSocket:
        #作为服务端提供ws服务可配置
        server:
          # 服务端的端口号
          port: 8888

    bot2:
      #是否启用
      enable: false
      #机器人的qq号
      qq: 222222222
      #机器人的webSocket配置
      webSocket:
        #作为客户端接入ws服务
        client:
          # 需要连接的ws地址
          serverUrl: ws://localhost:3001

  #类型：qq（QQ官方机器人）
  qq:
    #自定义机器人名称
    bot3:
      #是否启用
      enable: false
      #qq官方机器人必须配置
      appId:
      clientSecret:

# 数据库配置
mysql:
  address: localhost:3306/bb_bot
  username: root
  password: root

file:
  #静态文件保存目录
  path: /bot/static/

#----------------------可选配置--------------------------------------------------------
# 服务配置
server:
  # 服务器的ip
  ip: 127.0.0.1
  # 服务器的HTTP端口，默认为8080
  port: 8199

spring:
  #配置文件
  profiles:
    active: local
  #mysql druid数据源相关配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://${mysql.address}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
      username: ${mysql.username}
      password: ${mysql.password}
      # 初始连接数
      initialSize: 10
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 30
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: false
      statViewServlet:
        enabled: false

rest:
  # 代理相关配置
  proxyIp:
  proxyPort:

#ai聊天相关配置
aiChat:
  #如果为0则不回复，否则随机一个0-1之间的数，回复数值大于此数值则回复
  replyNum: 0.95d

# chatGPT相关配置
chatGPT:
  apiKey:

tencent:
  #腾讯云对象存储配置
  cos:
    secretId:
    secretKey:

#文件服务器相关配置
fileClient:
  # local (默认本地存储，没有文件服务器)，sftp (sftp作为文件服务), tencentCos(腾讯云对象存储，但是qq官方机器人访问自己家腾讯云对象存储的外链会说ip被ban就离谱)
  type: local

#  #sftp相关配置
#  type: sftp
#  sftp:
#    host: 127.0.0.1
#    port: 22
#    username: root
#    password: xxxxx
#    #远程可访问的目录
#    remoteDir: /root/bbBot/static/
#    #可被公网访问的地址
#    remoteReadAddress: http://127.0.0.1:30080/bbBotStatic/